### ISSUE TITLE
http://localhost:3001/list/foo

### ISSUE THREAD

**Issue by davidascher** [participedia/api#138]
breaks ugly:

```
{
OK: false,
error: {
name: "QueryFileError",
stack: "QueryFileError: Error: ENOENT: no such file or directory, open '/Users/da/personal_src/api/api/sql/list_references.sql' at new QueryFileError (/Users/da/personal_src/api/node_modules/pg-promise/lib/errors/queryFile.js:41:22) at QueryFile.prepare (/Users/da/personal_src/api/node_modules/pg-promise/lib/queryFile.js:184:21) at Database.$query (/Users/da/personal_src/api/node_modules/pg-promise/lib/query.js:50:19) at Database.<anonymous> (/Users/da/personal_src/api/node_modules/pg-promise/lib/query.js:227:23) at config.$npm.connect.pool.then.db (/Users/da/personal_src/api/node_modules/pg-promise/lib/database.js:238:42) at tryCatcher (/Users/da/personal_src/api/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Users/da/personal_src/api/node_modules/bluebird/js/release/promise.js:510:31) at Promise._settlePromise (/Users/da/personal_src/api/node_modules/bluebird/js/release/promise.js:567:18) at Promise._settlePromiseCtx (/Users/da/personal_src/api/node_modules/bluebird/js/release/promise.js:604:10) at Async._drainQueue (/Users/da/personal_src/api/node_modules/bluebird/js/release/async.js:138:12) at Async._drainQueues (/Users/da/personal_src/api/node_modules/bluebird/js/release/async.js:143:10) at Immediate.Async.drainQueues (/Users/da/personal_src/api/node_modules/bluebird/js/release/async.js:17:14) at runCallback (timers.js:800:20) at tryOnImmediate (timers.js:762:5) at processImmediate [as _immediateCallback] (timers.js:733:5)",
message: "ENOENT: no such file or directory, open '/Users/da/personal_src/api/api/sql/list_references.sql'",
file: "/Users/da/personal_src/api/api/sql/list_references.sql",
options: {
debug: false,
minify: true,
compress: false
}
}
}
```

**Comment by dethe** [comment]
Fixed as part of PR #134
