### ISSUE TITLE
jesi running into issues submitting cases

### ISSUE THREAD

**Issue by davidascher** [participedia/api#150]
```
Jun 16 16:19:42 participedia-api app/web.1:  Executing query WITH authors_list AS ( SELECT array_agg(( authors.user_id, authors.timestamp, users.name )::author) authors FROM authors, users WHERE authors.user_id = users.id AND authors.thingid = '4565' ), full_thing AS ( SELECT "cases".*, COALESCE("cases".other_images, '{}') other_images, COALESCE("cases".files, '{}') files, COALESCE("cases".videos, '{}') videos, COALESCE("cases".tags, '{}') tags, COALESCE("cases".links, '{}') links, localized_texts.body, localized_texts.title, authors_list.authors, get_related_nouns('case', 'case', '4565', 'en' ) AS related_cases, get_related_nouns('method', 'case', '4565', 'en' ) AS related_methods, get_related_nouns('organization', 'case', '4565', 'en' ) AS related_organizations, bookmarked("cases".type, '4565', 224987) FROM "cases", localized_texts, authors_list WHERE "cases".id = localized_texts.thingid AND localized_texts.language = 'en' AND "cases".id = '4565' ) SELECT to_json(full_thing.*) results FROM full_thing ; 
Jun 16 16:19:42 participedia-api app/web.1:  Executing query REFRESH MATERIALIZED VIEW search_index_en; 
Jun 16 16:19:46 participedia-api app/web.1:  error: Exception in PUT /case/4565 => Error: Can't set headers after they are sent. 
Jun 16 16:19:46 participedia-api app/web.1:  Trace: Error: Can't set headers after they are sent. 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.setHeader (_http_outgoing.js:371:11) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.header (/app/node_modules/express/lib/response.js:719:10) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.send (/app/node_modules/express/lib/response.js:164:12) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.json (/app/node_modules/express/lib/response.js:250:15) 
Jun 16 16:19:46 participedia-api app/web.1:      at editById (/app/api/helpers/things.js:283:23) 
Jun 16 16:19:46 participedia-api app/web.1:      at editById (/app/api/helpers/things.js:286:15) 
Jun 16 16:19:46 participedia-api app/web.1:  Possibly Unhandled Rejection at: Promise  Promise { 
Jun 16 16:19:46 participedia-api app/web.1:    <rejected> Error: Can't set headers after they are sent. 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.setHeader (_http_outgoing.js:371:11) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.header (/app/node_modules/express/lib/response.js:719:10) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.send (/app/node_modules/express/lib/response.js:164:12) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.json (/app/node_modules/express/lib/response.js:250:15) 
Jun 16 16:19:46 participedia-api app/web.1:      at editById (/app/api/helpers/things.js:287:23) }  reason:  Error: Can't set headers after they are sent. 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.setHeader (_http_outgoing.js:371:11) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.header (/app/node_modules/express/lib/response.js:719:10) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.send (/app/node_modules/express/lib/response.js:164:12) 
Jun 16 16:19:46 participedia-api app/web.1:      at ServerResponse.json (/app/node_modules/express/lib/response.js:250:15) 
Jun 16 16:19:46 participedia-api app/web.1:      at editById (/app/api/helpers/things.js:287:23) 
Jun 16 16:20:17 participedia-api app/web.1:  OPTIONS /case/4565 204 0.112 ms - - 
```

this feels easy to dig into, just haven't yet.

**Comment by davidascher** [comment]
fyi @dethe

**Comment by dethe** [comment]
Is this when quick submitting a new case or submitting an edited case? On my local instance I can't replicate -- editing a case works, and I can't submit a new case because of https://github.com/participedia/frontend/issues/470

I have seen an error like this once before, which worries me that it might be a timing issue that only crops up once in a while. Any reliable way to replicate would be appreciated.

**Comment by dethe** [comment]
Can replicate by logging in with non-email/password, although Jesi was also able to repro after creating a new email/password login.
