### ISSUE TITLE
case edit: problem saving evaluation_reports 

### ISSUE THREAD

**Issue by ascott** [participedia/api#513]
when saving `evaluation_reports` i get the following error: 
i think it's an issue with the column type in postgres. it should be the same column type as photos and files. 

```
 1: { error: malformed record literal: "("https://s3.amazonaws.com/uploads.participedia.xyz/8e0c59f8-53df-47a9-8e53-92a7bae98daa-TEXT.TXT","",,TEXT.TXT)"
            at Connection.parseE (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:555:11)
            at Connection.parseMessage (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:380:19)
            at Socket.<anonymous> (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:120:22)
            at Socket.emit (events.js:193:13)
            at Socket.EventEmitter.emit (domain.js:481:20)
            at addChunk (_stream_readable.js:296:12)
            at readableAddChunk (_stream_readable.js:277:11)
            at Socket.Readable.push (_stream_readable.js:232:10)
            at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
          name: 'error',
          length: 220,
          severity: 'ERROR',
          code: '22P02',
          detail: 'Too many columns.',
          hint: undefined,
          position: '778',
          internalPosition: undefined,
          internalQuery: undefined,
          where: undefined,
          schema: undefined,
          table: undefined,
          column: undefined,
          dataType: undefined,
          constraint: undefined,
          file: 'rowtypes.c',
          line: '267',
          routine: 'record_in' 
}
```

**Comment by dethe** [comment]
Fixed by #519
