### ISSUE TITLE
to figure out

### ISSUE THREAD

**Issue by davidascher** [participedia/api#66]
```
error: Error deleting bookmark error: invalid input syntax for integer: "'1109'"
    at Connection.parseE (/Users/da/src/participedia/api/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/da/src/participedia/api/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/da/src/participedia/api/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:563:20)
```

**Comment by davidascher** [comment]
In general, I think the bookmarking code is quote escaping everything too much, not sure where.
