### ISSUE TITLE
[DEV] Collections

### ISSUE THREAD

**Issue by ascott** [participedia/api#783]
Design issue: https://github.com/participedia/api/issues/771

@paninee 
- [x] add a column to the cases table called ‘collections’
    - this column should be like `specific_topics` in that it stores an array of strings
- [x] allow collection field to be filtered in search

@ascott  
- [x] add collections field to edit and reader view
- [x] add collections field to search filters ui
- [x] add collections keys to shared options file 
    - participedia_team [Participedia Team]
    - gov_of_canada [Government of Canada]
    - sciencewise [Sciencewise]
    - coady_students [Coady Students]
    - usoton_students [USoton Students]
    - uarkansas_students [U Arkansas Students]
- [x] add collection field strings to en.js to be translated

**Comment by ascott** [comment]
@paninee i started a branch for this feature and the allowed keys to the shared-field-option.js file. let me know if you need anything else from me on this! 

https://github.com/participedia/api/compare/feature/collections?expand=1

**Comment by jesicarson** [comment]
@ascott @paninee the explanatory and modal text for collections has been updated [in this doc](https://docs.google.com/document/d/1kmv3EhA9UT0soeTqdnuyJP04P70AUhLVZcMU4lxartM/edit?ts=5dc5b15c). and we're going check in with the universities (coady, usoton, arkansas) to make sure they want a collection and if so what they prefer to call it. is it ok to update those later?

**Comment by ascott** [comment]
@jesicarson thanks, and yes, we can update those before we launch

**Comment by ascott** [comment]
@paninee i added the front changes to this branch, and ran the migration, but i'm getting this error when i try to save a collection:
```
Possibly Unhandled Rejection at: Promise for reason BatchError {
    stat: { total: 3, succeeded: 2, failed: 1, duration: 13 }
    errors: [
        2: Error: Property 'collections' doesn't exist.
            at query.replace.name (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/formatting.js:163:19)
            at String.replace (<anonymous>)
            at Object.object (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/formatting.js:143:22)
            at Object.$formatQuery [as formatQuery] (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/formatting.js:297:29)
            at Task.$query (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/query.js:133:40)
            at Task.<anonymous> (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/query.js:259:23)
            at Task.query (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:119:34)
            at Task.obj.none (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:504:30)
            at Task.db.tx.t (/Users/alannascott/code/participedia/api/api/controllers/case.js:240:13)
            at callback (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:201:21)
            at begin.then (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:261:25)
        From previous event:
            at Object.execute (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:261:14)
            at config.$npm.connect.pool.then.db (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:1581:45)
            at processImmediate (internal/timers.js:443:21)
            at process.topLevelDomainCallback (domain.js:136:23)
        From previous event:
            at Database.taskProcessor (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:1578:18)
            at Database.obj.tx (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:1453:34)
            at postCaseUpdateHttp (/Users/alannascott/code/participedia/api/api/controllers/case.js:236:16)
    ]
} {}
```

any ideas?

**Comment by paninee** [comment]
> @paninee i added the front changes to this branch, and ran the migration, but i'm getting this error when i try to save a collection:
> 
> ```
> Possibly Unhandled Rejection at: Promise for reason BatchError {
>     stat: { total: 3, succeeded: 2, failed: 1, duration: 13 }
>     errors: [
>         2: Error: Property 'collections' doesn't exist.
>             at query.replace.name (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/formatting.js:163:19)
>             at String.replace (<anonymous>)
>             at Object.object (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/formatting.js:143:22)
>             at Object.$formatQuery [as formatQuery] (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/formatting.js:297:29)
>             at Task.$query (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/query.js:133:40)
>             at Task.<anonymous> (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/query.js:259:23)
>             at Task.query (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:119:34)
>             at Task.obj.none (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:504:30)
>             at Task.db.tx.t (/Users/alannascott/code/participedia/api/api/controllers/case.js:240:13)
>             at callback (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:201:21)
>             at begin.then (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:261:25)
>         From previous event:
>             at Object.execute (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/task.js:261:14)
>             at config.$npm.connect.pool.then.db (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:1581:45)
>             at processImmediate (internal/timers.js:443:21)
>             at process.topLevelDomainCallback (domain.js:136:23)
>         From previous event:
>             at Database.taskProcessor (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:1578:18)
>             at Database.obj.tx (/Users/alannascott/code/participedia/api/node_modules/pg-promise/lib/database.js:1453:34)
>             at postCaseUpdateHttp (/Users/alannascott/code/participedia/api/api/controllers/case.js:236:16)
>     ]
> } {}
> ```
> 
> any ideas?

fixed

**Comment by ascott** [comment]
@jesicarson this has been shipped to staging for testing!

**Comment by ascott** [comment]
- [ ] Need to update the names of the university collections to the following:
https://github.com/participedia/usersnaps/issues/933
- U Arkansas Students should be: "University of Arkansas Clinton School of Public Service"
- Coady Students should be: "Coady Institute Graduates"
- USoton Students should be: "University of Southampton Students"

- [  ]  add info icon/modal for collections field 
https://github.com/participedia/usersnaps/issues/934

**Comment by jesicarson** [comment]
@ascott Arkansas was updated to: "UA Clinton School of Public Service Students"

**Comment by ascott** [comment]
this is complete and on production now
